In [1]:
import numpy as np
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x[:2, :2]

array([[1, 2],
       [4, 5]])

In [5]:
x[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = np.arange(1, 40, 5).reshape(-1, 1)
y = np.arange(41, 80, 5)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 2, random_state = 42)

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
print(f'R2 Score (accuracy): {r2:.2f}')

print(x)
print(y)
print(y_pred)




R2 Score (accuracy): 1.00
[ 1  6 11 16 21 26 31 36]
[41 46 51 56 61 66 71 76]
[46. 66.]


In [17]:
import numpy as np
# Question A(i)
x = np.array([[12, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])
print(x)
# -> [[12  5  2  4]
#  [ 7  6  8  8]
#  [ 1  6  7  7]]

# Question A(ii)
subarray = x[:2, :3]
print(subarray)
# -> [[12  5  2]
#  [ 7  6  8]]

# Question A(iii)
subarray1 = x[:3, ::2]
print(subarray1)
# -> [[12  2]
#  [ 7  8]
#  [ 1  7]]

# Question A(iv)
subarray2 = x[::-1, ::-1]
print(subarray2)
# -> [[ 7  7  6  1]
#  [ 8  8  6  7]
#  [ 4  2  5 12]]


# Question B(a)
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

data = {
    'TV': [230.1, 44.5, 17.2, 151.5, 180.8],
    'Radio': [37.8, 39.3, 45.9, 41.3, 10.8],
    'Newspaper': [69.2, 45.1, 69.3, 58.5, 58.4],
    'Sales': [22.1, 10.4, 9.3, 18.5, 12.9]
}
df = pd.DataFrame(data)
# Features and target variable
X = df[['TV', 'Radio', 'Newspaper']]
y = df['Sales']

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 2, random_state = 42)
# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Calculate accuracy (R2 score)
r2 = r2_score(y_test, y_pred)
print(f'R2 Score (accuracy): {r2:.4f}')
# -> R2 Score (accuracy): -19.0094

# Question B(b)
new_data = np.array([[165.5, 20.0, 35.4]])
predicted_sales = model.predict(new_data)
print(f"Predicted sales: {predicted_sales[0]:.2f}")
# -> Predicted sales: 21.70

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]
R2 Score (accuracy): -19.0094
Predicted sales: 21.70


/home/linuxbrew/.linuxbrew/Cellar/python@3.11/3.11.4_1/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
