In [2]:
num1 = 1
num2 = 2
print(num1 + num2)

3


In [3]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
numbers

array([1, 2, 3, 4, 5])

In [6]:
numbers.shape

(5,)

In [7]:
numbers.size

5

In [8]:
two_dim_values = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Values of the array\n {0}".format(two_dim_values))

Values of the array
 [[1 2 3 4]
 [5 6 7 8]]


In [9]:
two_dim_values.size

8

In [10]:
two_dim_values.shape

(2, 4)

In [12]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [15]:
np.linspace(-1, 10, 50)

array([-1.        , -0.7755102 , -0.55102041, -0.32653061, -0.10204082,
        0.12244898,  0.34693878,  0.57142857,  0.79591837,  1.02040816,
        1.24489796,  1.46938776,  1.69387755,  1.91836735,  2.14285714,
        2.36734694,  2.59183673,  2.81632653,  3.04081633,  3.26530612,
        3.48979592,  3.71428571,  3.93877551,  4.16326531,  4.3877551 ,
        4.6122449 ,  4.83673469,  5.06122449,  5.28571429,  5.51020408,
        5.73469388,  5.95918367,  6.18367347,  6.40816327,  6.63265306,
        6.85714286,  7.08163265,  7.30612245,  7.53061224,  7.75510204,
        7.97959184,  8.20408163,  8.42857143,  8.65306122,  8.87755102,
        9.10204082,  9.32653061,  9.55102041,  9.7755102 , 10.        ])

In [17]:
np.random.randn(5, 5)

array([[ 0.34558713,  1.1522952 ,  1.59232167,  1.81489227, -1.23448402],
       [ 0.79143931, -1.21797794,  0.63652585,  0.35168003, -0.50004036],
       [ 1.52652609, -0.16590783,  0.35414852,  0.37069303,  0.15015689],
       [ 0.91995718, -0.40974267,  0.61267299, -0.82359318,  1.38135324],
       [ 0.42098298,  1.07116496,  1.7615201 , -1.59196462, -1.32328031]])