In [2]:
num1 = 1
num2 = 2
print(num1 + num2)

3


In [3]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
numbers

array([1, 2, 3, 4, 5])

In [6]:
numbers.shape

(5,)

In [7]:
numbers.size

5

In [8]:
two_dim_values = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Values of the array\n {0}".format(two_dim_values))

Values of the array
 [[1 2 3 4]
 [5 6 7 8]]


In [9]:
two_dim_values.size

8

In [10]:
two_dim_values.shape

(2, 4)

In [12]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [15]:
np.linspace(-1, 10, 50)

array([-1.        , -0.7755102 , -0.55102041, -0.32653061, -0.10204082,
        0.12244898,  0.34693878,  0.57142857,  0.79591837,  1.02040816,
        1.24489796,  1.46938776,  1.69387755,  1.91836735,  2.14285714,
        2.36734694,  2.59183673,  2.81632653,  3.04081633,  3.26530612,
        3.48979592,  3.71428571,  3.93877551,  4.16326531,  4.3877551 ,
        4.6122449 ,  4.83673469,  5.06122449,  5.28571429,  5.51020408,
        5.73469388,  5.95918367,  6.18367347,  6.40816327,  6.63265306,
        6.85714286,  7.08163265,  7.30612245,  7.53061224,  7.75510204,
        7.97959184,  8.20408163,  8.42857143,  8.65306122,  8.87755102,
        9.10204082,  9.32653061,  9.55102041,  9.7755102 , 10.        ])

In [4]:
np.random.randn(5, 5)

array([[ 0.08950332,  0.90773659,  0.5950825 ,  0.14243658, -1.21218506],
       [-1.25983936, -0.59195428,  1.07828439,  0.29342914,  0.25324914],
       [-0.11698315, -0.56723805,  0.03982303,  1.04003338, -0.31719207],
       [ 1.39464063,  0.43691891, -0.89694465, -0.19319497,  0.94421975],
       [-0.11670699, -0.48192434,  1.24414354, -0.06337711, -2.12087432]])

In [5]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [7]:
np.eye(5, dtype = int)

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')