2. MULTI DIMENSIONAL ARRAYS WITH NUMPY
+ Numpy is a useful library for array creation and manipulation in python. It can be used for both one-dimensional and multi-dimensional arrays.

In [1]:
import numpy as np  # Imports the numpy library

+ To create a simple multidimensional array from scratch, you can just explicitly define the arrays elements using numpy

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Creates a 2x3 numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Creates a 3x3 numpy array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

+ Multidimensional arrays have both size and shape. Shape refers to how the array is arranged while size refers to the number of elements in the array.

In [4]:
arr.shape

(3, 3)

In [5]:
arr.size

9

+ There are different types of arrays and therefore different ways of making them from scratch. One such array is a zeros array. It is created with the shape it should have as well as its elements' data type.

In [8]:
arr = np.zeros((2, 4), dtype = int)  # Creates a 2x4 numpy array filled with zeros
arr = np.ones((3, 3), dtype = int)  # Creates a 3x3 numpy array filled with ones
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

+ There is also the "identity" function that's used to create identity matrices. It has one argument which is the number of rows/columns the matrix has

In [11]:
arr = np.identity(5)
arr = np.identity(8)
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

+ Another useful array creation method is "random.randint". The function has two parameters: the limit for the intended array's values and its shape since it's a multi-dimensional array.
+ It is frequently used with "random.seed(0)" to retain values for reproduction.

In [15]:
np.random.seed(0)
arr = np.random.randint(12, size = (4, 3))
arr

array([[ 5,  0,  3],
       [11,  3,  7],
       [ 9,  3,  5],
       [ 2,  4,  7]])