Data manipulation in Python is nearly synonymous with NumPy array manipulation. The numeric functionality of numpy is orchestrated by ndarray, a multi-dimensional array object that is the coredatacontainer for all of the numpy operations.

In [70]:
import numpy as np

array([1, 2, 3, 4, 5])

In [107]:
# 1. CREATING ARRAYS
# Arrays can be created in multiple ways in numpy. A single dimensional array can be created fromPythonlists using np.array() 
# method as shown below
numbers = np.array([1, 2, 3, 4, 5])
numbers

# The shape attribute of the array object returns the size of each dimension in the form of (row, columns), while the size returns
# the total size of the array:
print(f"Array shape: {numbers.shape}")
print(f"Array size: {numbers.size}")

Array shape: (5,)
Array size: 5


In [71]:
numbers.shape

(5,)

In [72]:
numbers.size

5

In [73]:
two_dim_values = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Values of the array\n {0}".format(two_dim_values))

Values of the array
 [[1 2 3 4]
 [5 6 7 8]]


In [74]:
two_dim_values.size

8

In [75]:
two_dim_values.shape

(2, 4)

In [76]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [79]:
np.linspace(-1, 10, 50)

array([-1.        , -0.7755102 , -0.55102041, -0.32653061, -0.10204082,
        0.12244898,  0.34693878,  0.57142857,  0.79591837,  1.02040816,
        1.24489796,  1.46938776,  1.69387755,  1.91836735,  2.14285714,
        2.36734694,  2.59183673,  2.81632653,  3.04081633,  3.26530612,
        3.48979592,  3.71428571,  3.93877551,  4.16326531,  4.3877551 ,
        4.6122449 ,  4.83673469,  5.06122449,  5.28571429,  5.51020408,
        5.73469388,  5.95918367,  6.18367347,  6.40816327,  6.63265306,
        6.85714286,  7.08163265,  7.30612245,  7.53061224,  7.75510204,
        7.97959184,  8.20408163,  8.42857143,  8.65306122,  8.87755102,
        9.10204082,  9.32653061,  9.55102041,  9.7755102 , 10.        ])

In [80]:
np.random.randn(5, 5)

array([[-0.88778575, -1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656,  0.3869025 ],
       [-0.51080514, -1.18063218, -0.02818223,  0.42833187,  0.06651722]])

In [81]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [82]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [83]:
np.random.randint(10, size = 6)

array([9, 0, 2, 7, 2, 9])

In [84]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x1

array([5, 0, 3, 3, 7, 9])

In [85]:
np.random.seed(0)
x2 = np.random.randint(20, size = (7, 8))
x2

array([[12, 15,  0,  3,  3,  7,  9, 19],
       [18,  4,  6, 12,  1,  6,  7, 14],
       [17,  5, 13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3, 17, 19],
       [19, 19, 14,  7,  0,  1,  9,  0],
       [10,  3, 11, 18,  2,  0,  0,  4],
       [ 5,  6,  8, 17, 15,  4,  9, 10]])

In [86]:
print(int(x1[0]))
print(int(x2[0, 0]))
print(int(x1[-1]))
print(int(x2[-1, -1]))

5
12
9
10


In [91]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
x = np.arange(1, 6)
print(x.shape)
x4 = x.reshape(1, 5)
print(x4.shape)

x5 = x[np.newaxis,:]
print(x5)

x6 = x.reshape(1, 5)

(5,)
(1, 5)
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [104]:
x7 = x[:, np.newaxis]
x7[3, 0] = 3
x7

array([[1],
       [2],
       [3],
       [3],
       [5]])