In [9]:
num1 = 1
num2 = 2
print(num1 + num2)

3


In [10]:
import numpy as np
numbers = np.array([1, 2, 3, 4, 5])
numbers

array([1, 2, 3, 4, 5])

In [11]:
numbers.shape

(5,)

In [12]:
numbers.size

5

In [13]:
two_dim_values = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Values of the array\n {0}".format(two_dim_values))

Values of the array
 [[1 2 3 4]
 [5 6 7 8]]


In [14]:
two_dim_values.size

8

In [15]:
two_dim_values.shape

(2, 4)

In [16]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [19]:
np.linspace(-1, 10, 50)

array([-1.        , -0.7755102 , -0.55102041, -0.32653061, -0.10204082,
        0.12244898,  0.34693878,  0.57142857,  0.79591837,  1.02040816,
        1.24489796,  1.46938776,  1.69387755,  1.91836735,  2.14285714,
        2.36734694,  2.59183673,  2.81632653,  3.04081633,  3.26530612,
        3.48979592,  3.71428571,  3.93877551,  4.16326531,  4.3877551 ,
        4.6122449 ,  4.83673469,  5.06122449,  5.28571429,  5.51020408,
        5.73469388,  5.95918367,  6.18367347,  6.40816327,  6.63265306,
        6.85714286,  7.08163265,  7.30612245,  7.53061224,  7.75510204,
        7.97959184,  8.20408163,  8.42857143,  8.65306122,  8.87755102,
        9.10204082,  9.32653061,  9.55102041,  9.7755102 , 10.        ])

In [20]:
np.random.randn(5, 5)

array([[ 0.85663192,  0.77947618, -1.01251707, -0.64128143,  0.07392365],
       [-1.42715208,  0.68655106, -0.91733376, -1.1647808 ,  0.54524463],
       [ 0.8294734 ,  0.48652181,  0.14163198, -0.31822691, -1.2572956 ],
       [ 0.35482718,  0.40032479,  1.12388538, -0.12948076,  0.52745844],
       [ 0.85337338, -0.23895164,  0.56023244, -1.25623866,  0.14807691]])

In [21]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
np.random.randint(10, size = 6)

array([8, 8, 1, 6, 7, 7])

In [61]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x1

array([5, 0, 3, 3, 7, 9])

In [62]:
np.random.seed(0)
x2 = np.random.randint(20, size = (7, 8))
x2

array([[12, 15,  0,  3,  3,  7,  9, 19],
       [18,  4,  6, 12,  1,  6,  7, 14],
       [17,  5, 13,  8,  9, 19, 16, 19],
       [ 5, 15, 15,  0, 18,  3, 17, 19],
       [19, 19, 14,  7,  0,  1,  9,  0],
       [10,  3, 11, 18,  2,  0,  0,  4],
       [ 5,  6,  8, 17, 15,  4,  9, 10]])

In [68]:
print(int(x1[0]))
print(int(x2[0, 0]))
print(int(x1[-1]))
print(int(x2[-1, -1]))

5
12
9
10
