1. ONE DIMENSIONAL ARRAYS WITH NUMPY
+ Numpy is a useful library for array creation and manipulation in python. It can be used for both one-dimensional and multi-dimensional arrays.

In [1]:
import numpy as np  # Imports the numpy library

+ To create a simple 1D array from scratch, you can just explicitly define the arrays elements using numpy

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

+ Arrays have both size and shape. Shape refers to how the array is arranged while size refers to the number of elements in the array.

In [3]:
arr.shape   # THis will return (6, ) which means the array contains 6 rows and 1 column

(6,)

In [4]:
arr.size

6

+ There are different types of arrays and therefore different ways of making them from scratch. One such array is a zeros array. It is created with the number of elements it should have as well as their data type.

In [8]:
arr = np.zeros(12, dtype = int)
# arr = np.zeros(5, dtype = float)
# arr = np.zeros(7, dtype = string)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

+ The "arange" function is also used to create arrays according to a linear arrangement. It is created by defining the starting element, the final element and the step size between elements.

In [28]:
# arr = np.arange(3, 12, 3)
# arr = np.arange(0, 34, 7)
# arr = np.arange(5, 30, 2)
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

+ Another useful array creation method is "random.randint". The function has two parameters: the limit for the intended array's values and its size.
+ It is frequently used with "random.seed(0)" to retain values for reproduction

In [21]:
np.random.seed(0)
# arr = np.random.randint(12, size = 4)
# arr = np.random.randint(15, size = 5)
arr = np.random.randint(3, size = 12)
arr

array([0, 1, 0, 1, 1, 2, 0, 2, 0, 0, 0, 2])

+ Array indexing is the primary method of accessing array elements. It is done by referring to the index of the required element.

In [27]:
x = np.arange(0, 10, 3) # -> array([0, 3, 6, 9])
# int(x[0])   # -> 0
int(x[3])   # -> 9

9

+ Within the same vein of accessing array elements there is array slicing. This is essentially obtaining subsets of arrays according to three aramenters: the starting index, ending index and step size.

In [61]:
np.random.seed(0)
x = np.random.randint(16, size = 10) # -> array([12, 15,  5,  0,  3, 11,  3,  7,  9,  3])
x[:5]   # Returns the first five elements -> array([12, 15,  5,  0,  3])
x[5:]   # Returns the last five elements -> array([11,  3,  7,  9,  3])
x[::2]  # Returns every other even element -> array([12,  5,  3,  3,  9])
x[1::2] # Returns every other odd element -> array([15,  0, 11,  7,  3])

# + When the step value is negative, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array.
x[::-1] # Reverses the array -> array([ 3,  9,  7,  3, 11,  3,  0,  5, 15, 12])
x[4::-2] # Returns every other element starting from the 4th index -> array([ 3,  5, 12])

# + Assigning values to a slice is used to propagate that value across the slice.
# x[:5] = 3   # Changes the array's first five elements to 3 -> array([ 3,  3,  3,  3,  3, 11,  3,  7,  9,  3])
# x[5:] = 19  # Changes the array's last five elements to 19 -> array([12, 15,  5,  0,  3, 19, 19, 19, 19, 19])
# x[::2] = 5  # Changes every even element to 5 -> array([ 5, 15,  5,  0,  5, 11,  5,  7,  5,  3])
# x[1::2] = 2 # Changes every odd element to 2 -> array([12,  2,  5,  2,  3,  2,  3,  2,  9,  2])
# x[::-1] = 0 # Reverses the array and sets all values to 0 -> array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
x[4::-2] = 0 # Changes every other element starting from the 4th index to 0 -> array([0, 15, 0, 0, 3, 11, 3, 7, 9, 3])
x

array([ 0, 15,  0,  0,  0, 11,  3,  7,  9,  3])