1. ONE DIMENSIONAL ARRAYS WITH NUMPY
+ Numpy is a useful library for array creation and manipulation in python. It can be used for both one-dimensional and multi-dimensional arrays.

In [1]:
import numpy as np  # Imports the numpy library

+ To create a simple 1D array from scratch, you can just explicitly define the arrays elements using numpy

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

+ Arrays have both size and shape. Shape refers to how the array is arranged while size refers to the number of elements in the array.

In [3]:
arr.shape   # THis will return (6, ) which means the array contains 6 rows and 1 column

(6,)

In [4]:
arr.size

6

+ There are different types of arrays and therefore different ways of making them from scratch. One such array is a zeros array. It is created with the number of elements it should have as well as their data type.

In [8]:
arr = np.zeros(12, dtype = int)
# arr = np.zeros(5, dtype = float)
# arr = np.zeros(7, dtype = string)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

+ The "arange" function is also used to create arrays according to a linear arrangement. It is created by defining the starting element, the final element and the step size between elements.

In [12]:
# arr = np.arange(3, 12, 3)
# arr = np.arange(0, 34, 7)
arr = np.arange(5, 30, 2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])